### PR TITLE
Added Folding Text support

### PR DESCRIPTION
**Pull request by raguay**
Hi,

I finally got it to work. This works on my system for the FoldingText.app program. Now I can have notes for my notes!

Will be working on others.

### CODE REVIEW

**Comment by jhoughjr** [comment]
Awesome! Often getting the scripts to work is a trial and error type of process, so it can take a lot of work.

That's great that you are delving into AppleScript.

My girlfriend is in the hospital currently so I've not been able to work on Ghostnlte since mid Wednesday.

But I will try and merge this in Monday depending on how the situation evolves.

Thank you for contributing and supporting Ghostnote!

**Comment by raguay** [comment]
I just added Scrivener support as well. Since Scrivener doesn't support scripting, I had to use system events to get the title. This approach will work for any program that doesn't support scripting.

**Comment by jhoughjr** [comment]
Yep, you are figuring it out! There are a few apps we had to resort to system events for. But using the title can be fragile if the app changes. It’s not the ideal solution, but sometimes is the best we can do for some apps.

I will try and merge in your changes today since I should have time to do some Ghostnote work.

Thanks again for contributing to Ghostnote.

**Comment by raguay** [comment]
I do a lot of applescript with Alfred Workflows and Keyboard Maestro 
hotkeys. I really do not like AppleScript, but it is usable. It would be 
nice to be able to use JavaScript for Automation instead.

Praying for your girlfriend.

Richard

Jimmy Hough Jr. wrote:

> Yep, you are figuring it out! There are a few apps we had to resort to
> system events for. But using the title can be fragile if the app
> changes. It’s not the ideal solution, but sometimes is the best we can
> do for some apps.
> 
> I will try and merge in your changes today since I should have time to
> do some Ghostnote work.
> 
> Thanks again for contributing to Ghostnote.
> 
> > On Jul 20, 2015, at 10:43 AM, Richard Guay

**Comment by jhoughjr** [comment]
I like the idea of AppleScript, but its problem is that there is no standard for apps’ terminology.
On Yosemite Javascript is supported by the Open Scripting Architecture implementation.

I haven’t tested it, but I think that a JS script would work with Ghostnote, at least the Paddle version since we use osascript to execute the script, and the JS scripts still return an Apple Event Descriptor. Feel free to test it.

**Pull request merged**
